### ISSUE TITLE
ETI-NI 

### ISSUE THREAD

**Issue by k-otixxx** [lars18th/satip-rtp#1]
I have success with Dablin player from Ubuntu to play ETI-NI from enigma2 set top box(from satellite feeds) with eti-tools installed.All satellite DAB feeds(12,5W,4,5E,7E,30E) work form me .
I want to use welle.io to test these streams.
@lars18th
Could you post some examples how to start realtime RTL-TCP server from set top box with eti-tools installed.

**Comment by lars18th** [comment]
See here: https://github.com/AlbrechtL/welle.io/issues/217#issuecomment-404227218

Off topic!

**Comment by andimik** [comment]
What DAB transmissions have you found on 30 East? Or do you mean 3 East?

**Comment by lars18th** [comment]
> What DAB transmissions have you found on 30 East? Or do you mean 3 East?

I don't see anything about 30ºE nor 3ºE of DAB enssambles.
Sorry!
